name: xUIDesign

on: push

jobs:
  super-lint:
    name: X UI Design
    runs-on: ubuntu-latest
    steps:
      - name: Run xUIDesign
        uses: gabboyajyan/xUIDesign@master
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
